### ISSUE TITLE
(Bitcoin 0.10) BIP 66: strict DER encoding for signatures

### ISSUE THREAD

**Issue by mjmacleod** [guldenpay/gulden-dev#14]
This BIP causes an increase in block version number, have a closer look at how it impacts gulden.

**Comment by Waterloodown** [comment]
Malcolm and Frank to decide on this point.

**Comment by cydg** [comment]
We could do it by using the block number we switch to core 0.10 instead.

**Comment by mjmacleod** [comment]
Waiting until closer to release to decide if we must bump the block version number now already  or if we can keep it for later...
