### ISSUE TITLE
Showing 20 GB blockchain data download when installing wallet

### ISSUE THREAD

**Issue by Waterloodown** [guldenpay/gulden-dev#29]
Just need to get this changed for 1.5.1

**Comment by cydg** [comment]
qt\intro.cpp
/* Minimum free space (in bytes) needed for data directory */
static const uint64_t GB_BYTES = 1000000000LL;
static const uint64_t BLOCK_CHAIN_SIZE = 20LL * GB_BYTES;

qt\forms\intro.ui (see sizeWarningLabel)
... At least %1GB of data ...

We don't even have 400MB with index, so setting
static const uint64_t BLOCK_CHAIN_SIZE = 1LL * GB_BYTES;
will give us plenty of time before we have to change it again.
